### ISSUE TITLE
There is an error in demo.ipynb

### ISSUE THREAD

**Issue by 283pm** [hysts/anime-face-detector#11]
First of all, thank you for sharing your program.

Today I tried to run the program in GoogleColab and got the following error in the import anime_face_detector section.
Do you know any solutions?

Thank you.

ImportError                               Traceback (most recent call last)
[<ipython-input-23-53e3c28fb569>](https://localhost:8080/#) in <module>()
      5 import numpy as np
      6 
----> 7 import anime_face_detector

7 frames
[/usr/lib/python3.7/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: /usr/local/lib/python3.7/dist-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol:_ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

**Comment by hysts** [comment]
Hi, @283pm 
Thanks for reporting this. I've just updated the notebook. I think the error was caused because the default version of torch in Colab was updated.
I'll close this issue, but feel free to reopen if you still have errors.
