### ISSUE TITLE
how to implement anime face identification with this detector

### ISSUE THREAD

**Issue by rsindper** [hysts/anime-face-detector#12]
Thanks for sharing such a nice work! I was wondering if it is possible to implement **anime face identification** based on this detector. Do you have any plan on this? Will we have a good identification accuracy using this detector? Many thanks!

**Comment by hysts** [comment]
Hi, @rsindper 
I have no plans to do it, but I think it would be an interesting project to try. To create an anime face identification model, you first need to create a dataset with character face crops and labels. [Danbooru dataset](https://www.gwern.net/Danbooru2021) has tags with character names, so it will be useful for creating such a dataset. And you can use this repo to crop faces from the original images. But illustrations may contain multiple characters in it, you would need to clean up the dataset manually or come up with an idea to (semi-)automatically cleaning it up.
I do not have in-depth knowledge on face recognition, but I think arcface is a good model to try to fine-tune. I think it's common for face recognition pipelines to use landmark models to align faces, so I think you can use this repo for that as well.
