### ISSUE TITLE
Re-thinking anime(Illustration/draw/manga) character face detection

### ISSUE THREAD

**Issue by koke2c95** [hysts/anime-face-detector#3]
awesome work!

especially [face clustering](https://github.com/hysts/anime-face-detector/blob/main/assets/cluster_mean.jpg) very neat

### this work reminds me of
How can Illustration be aligned and what can I do with these 2d landmark?

Scaling and rotating images and crop: [FFHQ aligned code](https://github.com/happy-jihye/FFHQ-Alignment/blob/master/Anime-Face-Alignment/ffhq_align.py) and [webtoon result](https://github.com/happy-jihye/FFHQ-Alignment/blob/master/Anime-Face-Alignment/README.md)

[Artstation-Artistic-face-HQ]( https://onion-liu.github.io/BlendGAN) which counts as Illustration Use FFHQ aligned

and new FFHQ aligned [https://arxiv.org/abs/2109.09378](https://twitter.com/Buntworthy/status/1440244852944359425)

but anime Illustration is not the same as real FFHQ, where perspective-related (pose) means destroying the centre, and local parts exaggeration destroying the global

#### [**DO.1**] directly k-mean dictionary (run a dataset) proximity aligned
Mention [this analysis](https://faculty.idc.ac.il/arik/site/foa/face-of-art.asp)

#### [**DO.2**] because there are not many features can use, add continuous 2D spatial feature (pred), more point and [even beyond](https://www.semanticscholar.org/paper/RetinaFace%3A-Single-Shot-Multi-Level-Face-in-the-Deng-Guo/a069bce9492641698515498d920c22f79c6d2079/figure/0)
this need hack model (might proposed)

#### [**DO.3**] Should be used directly as a filter to assist with edge extraction (maximum reserve features)
guide VAE, [SGF generation](https://github.com/KYM384/SGF), or [anime cross image Synthesis](https://github.com/endo-yuki-t/Fewshot-SMIS)

if the purpose is not to train the generation model, probably use is to extend the dataset.
if training to generate models, will greatly effect generated [eye+chin centre aligned](https://www.youtube.com/watch?v=UKQ3_By9vGo)
visual lines don't keeping real image features [just  polylines](https://github.com/shalebark/anime-styled-face-alignment)

#### Or need more key points in clustering, det box pts (easy [**DO.4**]), and beyond to the whole image 

**and thank for your reading this**

**Comment by hysts** [comment]
Interesting! It seems there are a lot of related works and areas. I knew some of them, but I didn't know the others. Thank you for letting me know. I'll check them out when I have time.
By the way, I trained these models, as I wanted to try training StyleGAN with aligned anime face images, but couldn't find a good landmark model.
