### ISSUE TITLE
大神看看我

### ISSUE THREAD

**Issue by Echo-minn** [hysts/anime-face-detector#4]
我是OpenMMLab的，看见这个repo觉得很有意思，想找你约稿，可以嘛！（加这个vx号联系: OpenMMLabwx）

**Comment by hysts** [comment]
Hi, @Echo-minn 

Sorry, I don't speak Mandarin, so I'm not entirely sure what you mean, but according to Google translate and DeepL, it seems you are a member of OpenMMLab and found this repo interesting, right?

If so, thank you very much. Thanks to the OpenMMLab tools, it was really easy to try training models. Of course, annotating training data was very time-consuming and tough, though. But in other words, with the OpenMMLab tools, all I had to do was to create training data, so I really appreciate your work.
