### ISSUE TITLE
Question about the annotation tool for landmark

### ISSUE THREAD

**Issue by mrbulb** [hysts/anime-face-detector#6]
Thanks for your great work! 
May I ask which tool do you use to annotate the landmarks?
I find the detector seems to perform not so well on the manga images. So I want to manually annotate some manga images.
Besides, when you trained the landmarks detector, did you train the model from scratch or fine-tune on the pretrained mmpose model?

**Comment by hysts** [comment]
Hi, @mrbulb 

> May I ask which tool do you use to annotate the landmarks?

I've tried a couple of tools, and I'd recommend [cvat](https://github.com/openvinotoolkit/cvat).

> I find the detector seems to perform not so well on the manga images. So I want to manually annotate some manga images.

I see. All the training data I used were illustrations, and I didn't include grayscale images or faces with large deformations (e.g. faces with exaggerated expressions), which I think are common in manga images. So I guess that's the reason it doesn't perform well on them.
And, as you mentioned, I think it's a good idea to manually annotate manga images and use them to retrain a model.
FYI, https://github.com/hysts/anime-face-detector/issues/5#issuecomment-971493034 might be helpful.

> Besides, when you trained the landmarks detector, did you train the model from scratch or fine-tune on the pretrained mmpose model?

I fine-tuned the model from [this pretrained model](https://github.com/open-mmlab/mmpose/blob/master/configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_dark_wflw.md).

**Comment by mrbulb** [comment]
> Hi, @mrbulb
> 
> > May I ask which tool do you use to annotate the landmarks?
> 
> I've tried a couple of tools, and I'd recommend [cvat](https://github.com/openvinotoolkit/cvat).
> 
> > I find the detector seems to perform not so well on the manga images. So I want to manually annotate some manga images.
> 
> I see. All the training data I used were illustrations, and I didn't include grayscale images or faces with large deformations (e.g. faces with exaggerated expressions), which I think are common in manga images. So I guess that's the reason it doesn't perform well on them. And, as you mentioned, I think it's a good idea to manually annotate manga images and use them to retrain a model. FYI, [#5 (comment)](https://github.com/hysts/anime-face-detector/issues/5#issuecomment-971493034) might be helpful.
> 
> > Besides, when you trained the landmarks detector, did you train the model from scratch or fine-tune on the pretrained mmpose model?
> 
> I fine-tuned the model from [this pretrained model](https://github.com/open-mmlab/mmpose/blob/master/configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_dark_wflw.md).

Thank you for offering the training details! It really helps me a lot:smile:
