### ISSUE TITLE
Citation Issue

### ISSUE THREAD

**Issue by zeachkstar** [hysts/anime-face-detector#8]
Hi, @hysts  

First of all, thank you so much for the great work!

I'm a graduate student and have used your pretrained model to generate landmark points as ground truth.
I'm currently finishing up my thesis writing and want to cite your github repo.

I don't known if I overlooked something, but I couldn't find the citation information in the README page. 
Is there anyway to cite this repo?

Thank you.

**Comment by hysts** [comment]
Hi, @zeachkstar 
Thank you for your interest in this repo. I'm not sure of the best practices for citing GitHub repos, but I will add the following citation information to the README, following [mmcv](https://github.com/open-mmlab/mmcv#citation) and [big_vision](https://github.com/google-research/big_vision#citing-the-codebase).

```bibtex
@misc{anime-face-detector,
  author = {hysts},
  title = {Anime Face Detector},
  year = {2021},
  howpublished = {\url{https://github.com/hysts/anime-face-detector}}
}
```

**Comment by zeachkstar** [comment]
Thanks for your reply, it really helps me a lot.
