### ISSUE TITLE
Gradio demo on blocks organization

### ISSUE THREAD

**Issue by AK391** [hysts/anime-face-detector#9]
Hi, thanks for making a gradio demo for this on Huggingface https://huggingface.co/spaces/hysts/anime-face-detector, looks great with the new 3.0 design as well. Gradio has a event for the new Blocks API https://huggingface.co/Gradio-Blocks, it would be great if you can join to make a blocks version of this demo or another demo thanks!

**Comment by hysts** [comment]
Hi, @AK391 
Thanks for letting me know of the event. Sounds interesting. I'm not familiar with the Blocks feature yet, but I'll see if I can make a demo that utilizes the feature.
